#!/usr/bin/env python

"""
Start up script

This just acts to intialise a Qt application and pass any terminal arguments into the PKView application
"""

from __future__ import division, unicode_literals, print_function

import argparse
from PySide import QtGui
from pkview.pkviewer import WindowAndDecorators
import sys
import resource

if __name__ == '__main__':

    """
    Parse any input arguments and run the application
    """

    # Parse input arguments to pass info to GUI
    parser = argparse.ArgumentParser()
    parser.add_argument('--image', help='DCE-MRI nifti file location', default=None, type=str)
    parser.add_argument('--roi', help='ROI nifti file location', default=None, type=str)
    parser.add_argument('--overlay', help='Overlay nifti file location', default=None, type=str)
    parser.add_argument('--overlaytype', help='Type of overlay', default=None, type=str)
    args = parser.parse_args()

    # Initialise the PKView application
    app = QtGui.QApplication(sys.argv)
    app.setStyle('plastique')  # windows, motif, cde, plastique, windowsxp, macintosh
    app.setGraphicsSystem('native')  ## work around a variety of bugs in the native graphics system

    stFile = "darkorange.stylesheet"
    with open(stFile, "r") as fs:
        app.setStyleSheet(fs.read())

    # Pass arguments from the terminal (if any) into the main application
    ex = WindowAndDecorators(args.image, args.roi, args.overlay, args.overlaytype)
    sys.exit(app.exec_())